export const skills = [
  { name: "git", percent: 60 },
  { name: "scrum (work with jira software)", percent: 60 },
  { name: "html", percent: 80 },
  { name: "css", percent: 80 },
  { name: "sass", percent: 60 },
  { name: "flex-box", percent: 90 },
  { name: "grid", percent: 70 },
  { name: "Responsive design (mobile-first website)", percent: 80 },
  { name: "Progressive Web App (pwa)", percent: 50 },
  { name: "Bootstrap", percent: 80 },
  { name: "Material-UI", percent: 80 },
  { name: "Ant design", percent: 80 },
  { name: "umi , work on a dashboard panel with ant design pro", percent: 60 },
  { name: "javascript(es6)", percent: 80 },
  { name: "typescript(i had to learn it but i glad i did it)", percent: 50 },
  { name: "Axios", percent: 80 },
  { name: "reactjs", percent: 80 },
  { name: "React hooks (can write reusable hooks) advance", percent: 80 },
  { name: "React context", percent: 80 },
  { name: "Redux", percent: 60 },
  { name: "Redux-saga", percent: 60 },
  { name: "Nextjs framework for ssr rendering in reactjs", percent: 70 },
  { name: "css in jss(styled-components)", percent: 50 },
  {
    name: "testing react apps (with react-testing-library && e2e with cypress)",
    percent: 60,
  },
  { name: "eslint , work and config eslint", percent: 50 },
  { name: "nodejs", percent: 50 },
  { name: "express", percent: 50 },
  { name: "mongodb", percent: 30 },
  {
    name: "vim , i config vim in vs code and benefits both",
    percent: 50,
  },
];
