export const skills = [
  { name: "git", percent: 50 },
  { name: "html", percent: 80 },
  { name: "css", percent: 80 },
  { name: "flex-box", percent: 90 },
  { name: "grid", percent: 70 },
  { name: "Responsive design (mobile-first website)", percent: 80 },
  { name: "Progressive Web App (pwa)", percent: 50 },
  { name: "sass", percent: 60 },
  { name: "Bootstrap", percent: 80 },
  { name: "Material-UI", percent: 80 },
  { name: "Ant design", percent: 80 },
  { name: "javascript(es6)", percent: 80 },
  { name: "Axios", percent: 80 },
  { name: "JQuery", percent: 30 },
  { name: "reactjs", percent: 80 },
  { name: "React hooks (can write reusable hooks) advance", percent: 80 },
  { name: "React context", percent: 80 },
  { name: "Redux", percent: 60 },
  { name: "Redux-saga", percent: 60 },
  { name: "Nextjs framework for ssr rendering in reactjs", percent: 70 },
  { name: "css in jss(styled-components)", percent: 50 },
  { name: "testing react apps (with react-testing-library)", percent: 60 },
  { name: "nodejs", percent: 30 },
  { name: "express", percent: 50 },
  { name: "mongodb", percent: 30 },
];
