export const skills = [
  { name: "git", percent: 60 },
  { name: "scrum (work with jira software)", percent: 60 },
  { name: "html", percent: 80 },
  { name: "css", percent: 80 },
  { name: "sass", percent: 60 },
  { name: "css in jss(styled-components)", percent: 50 },
  { name: "Bootstrap", percent: 80 },
  { name: "Material-UI", percent: 80 },
  { name: "Ant design", percent: 80 },
  { name: "Responsive design (mobile-first website)", percent: 80 },
  { name: "Progressive Web App (pwa)", percent: 50 },
  { name: "javascript(es6)", percent: 80 },
  { name: "typescript", percent: 60 },
  { name: "Axios", percent: 80 },
  { name: "React js", percent: 80 },
  { name: "Formik", percent: 90 },
  { name: "Redux", percent: 60 },
  { name: "Redux-saga", percent: 60 },
  { name: "Nextjs framework for ssr rendering in reactjs", percent: 70 },
  {
    name: "testing react apps (with react-testing-library && e2e with cypress)",
    percent: 60,
  },
  { name: "eslint", percent: 50 },
  { name: "express", percent: 50 },
  { name: "mongodb", percent: 30 },
  {
    name: "vim , i config vim in vs code and benefits both",
    percent: 50,
  },
];
